### ISSUE TITLE
Ejabberd OMEMO

### ISSUE THREAD

**Issue by Duke690** [miranda-ng/miranda-ng#1417]
### Expected behavior
Since OMEMO works on ejabberd xmpp servers with clients like gajim, pidgin or conversations, I expected it to also work with Miranda NG.

### Actual behavior
Miranda NGs OMEMO implementation is not working with ejabberd xmpp servers (I tried blabber.im and a local installation of ejabberd). I successfully tried Miranda NGs OMEMO on Prosody servers.
Related:
#529 
#1255 

### Does it work in stable version?
no

### Steps to reproduce that behavior
 * Provide step-by-step instructions so we can reproduce the issue (We can't fix what we can't reproduce).
    1. Use a public ejabberd based xmpp server supporting OMEMO. 
    2. Try to start an OMEMO encrypted conversation miranda <-> miranda.
    3. Miranda keeps telling "Delivery failure: No valid OMEMO session exists"
    4. On both servers OMEMO encryption is working with gajim, pidgin and conversations.
 * Attach your VersionInfo.
Tried both:
Miranda NG Version: 0.95.9 alpha build #20248 (527c89ab4c) x64
Miranda NG Version: 0.95.8.1 build #19974 (b9ae2ad226) x64

**Comment by sss123next** [comment]
gajim have not standard compliant omemo implementation (much more aggressive), i have asked omemo xep creator about it, and he suggested to follow standard (xep) strictly, so i have not implemented workarounds used in gajim.
ejabberd had bugs in pubsub/pep in past, so events not always delivered to clients as it should (you can find my bugreports in ejabberd, which is currently fixed in git master at least)

as workaround on outdated/broken ejabberd you may try to login/logout few times on both sides so events start to forward as it should.

also please provide xml logs from both sides if possible.

**Comment by Duke690** [comment]
Hi thanks for your reply. I'm using the current ejabberd server version (18.04) where the fixes of your bugreport should be implemented already.
I created xml logs for both sides using Miranda NG Version: 0.95.8.1 build #19977 (0d7a2e72d2) x64 on both sides.
I also added my ejabberd config just in case. 
Thanks!
[user1.TXT](https://github.com/miranda-ng/miranda-ng/files/2123770/user1.TXT)
[user2.TXT](https://github.com/miranda-ng/miranda-ng/files/2123771/user2.TXT)
[ejabberd.txt](https://github.com/miranda-ng/miranda-ng/files/2123967/ejabberd.txt)

**Comment by sss123next** [comment]
first, my ejabberd settings related to this problem:
```
  mod_pubsub:
    access_createnode: pubsub_createnode
    ignore_pep_from_offline: false
    last_item_cache: true
    max_subscriptions_node: 100
    plugins:
      - "flat"
      - "pep"

```
and i HAVE this problem SOMETIME
next about your logs:

```
[15:17:43 1284] [JABBER_2] Jabber OMEMO: error: message does not encrypted for any session
s
```
this means what 
1. REMOTE side does not received event with your current device keys (may be caused by broken/misconfigured PEP on jabber server)
OR
2. failed to encrypt with public key provided for THIS device

second problem may be caused by outdated data in miranda db on THIS device, as current solution you need to manually clean db from outdated data which is located in <JABBER_PROFILE_NAME>/omemo_*

i have examined both of your logs, and do not see any errors on other side, so it looks like jabber server problem.

as for gajim, it have workaround for exact this kind of problems by not trusting server events only but manual polling for data updates, xep-0384 creator suggested to NOT implement this workaround.

from info you provided i can't suggest anything more than this.
you can also check ejabberd logs for errors and warnings, this may be helpful.

**Comment by sss123next** [comment]
1. it's not possible what miranda database does not have omemo entries, as i clearly see keys in log.
2. your miranda logs is incomplete, also  miranda xml log is much more readable, but network log provide additional debug so it's better to provide both full (uncut) logs
3. in current log from user1 is see reply for pubsub key array publication, but still does not see other necessary events from server (possible because your logs are incomplete)
4. omemo is not something special for jabber server side, you should check for pubsub/pep errors/warnings as it built on top of it
5. your ejabberd contain a lot of errors related to pubsub subscription and if you think what i will debug and setup your ejabberd server you wrong, and it's clearly not miranda side problems, also i suggest to not try to install it on windows anyway

```
2018-06-25 08:58:33.383 [debug] <0.641.0>@ejabberd_sm:do_route:693 sending to process <0.641.0>:
#iq{id = <<"mir_18">>,type = error,lang = <<"en">>,
    from =
       	#jid{
            user = <<"user_one">>,server = <<"localhost">>,resource = <<>>,
            luser = <<"user_one">>,lserver = <<"localhost">>,lresource = <<>>},
    to =
       	#jid{
            user = <<"user_two">>,server = <<"localhost">>,
            resource = <<"Miranda">>,luser = <<"user_two">>,
            lserver = <<"localhost">>,lresource = <<"Miranda">>},
    sub_els =
       	[#disco_info{node = <<>>,identities = [],features = [],xdata = []},
         #stanza_error{                                                                                    
             type = auth,code = 407,by = <<>>,                                                             
             reason = 'subscription-required',                                                             
             text = [#text{lang = <<"en">>,data = <<"Not subscribed">>}],                                  
             sub_els = []}],                                                                               
    meta = #{ip => {127,0,0,1}}}  
    2018-06-25 08:58:33.384 [debug] <0.641.0>@xmpp_socket:send:221 (tls|<0.641.0>) Send XML on stream = <<"<iq xml:lang='en' to='user_two@localhost/Miranda' from='user_one@localhost' type='error' id='mir_18'><query xmlns='http://jabber.org/protocol/disco#info'/><error code='40
7' type='auth'><subscription-required xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'/><text xml:lang='en' xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'>Not subscribed</text></error></iq>">>                                                                     
```
looks like your acl's or subscription is wrong.

**Comment by Duke690** [comment]
Please don't get me wrong, I'm not expecting you to do anything for me. Thanks for all the input you got me so far and your patience. Sorry for the incomplete logs : / didn't know that.

As you suggested I installed ejabberd 18.04 on a linux machine. I used the same configuration as posted before. I tried the following messengers with omemo support: Pidgin, Gajim, Androids Conversations and iOS ChatSecure. They are all working. 

I then checked my server with this tool: https://github.com/iNPUTmice/ComplianceTester - omemo encryption passed this test - Miranda still refuses to omemo encrypt messages. On the other hand I tried some more public jabber servers and found some where mirandas omemo is working. So I guess you are right, it's some kind of specific server configuration problem that has to be done for miranda.

As I said I dont expect you to do anything. I hereby kindly ask for a small hint on what other configurations on ejabberd side I have to do to get it running with mirandas omemo encryption. (besides your mod_pubsub configuration)
Since you say you got it working with an ejabberd server of yours could you maybe post your ejabberd.yml?

I would ask on ejabberds github - but since **only** Mirandas omemo refuses to work I still think this is the right place to ask.

**Comment by sss123next** [comment]
thank you for info, please share solution of your problem if you find it. also all complete miranda logs may be helpful.

my working ejaberd config:

```
loglevel: 4

log_rotate_size: 10485760
log_rotate_date: ""
log_rotate_count: 1

log_rate_limit: 100

default_db: sql


hosts:
   - "dark-alexandr.net"

route_subdomains: local

listen:
  - 
    port: 5222
    ip: "::"
    module: ejabberd_c2s
    certfile: "/etc/jabber/dark-alexandr.net.pem"
    dhfile: "/etc/jabber/dh9998.pem"
    starttls_required: true
    protocol_options:
       - "no_sslv3"
       - "no_tlsv1"
       - "no_tlsv1_1"
       - "CIPHER_SERVER_PREFERENCE"
    max_stanza_size: 65536
    ciphers: "DHE-RSA-CHACHA20-POLY1305:DHE-RSA-CAMELLIA256-SHA256:DHE-RSA-AES256-GCM-SHA384"
    shaper: c2s_shaper
    access: c2s
    zlib: true
    tls_compression: true
  - 
    port: 5269
    ip: "::"
    module: ejabberd_s2s_in
    transport: tcp
    zlib: true
    tls_compression: true


s2s_dhfile: "/etc/jabber/dhp4096.pem"
s2s_protocol_options:
   - "no_sslv3"
   - "no_tlsv1"
   - "CIPHER_SERVER_PREFERENCE"

s2s_ciphers: "CHACHA20:CAMELLIA:MEDIUM:HIGH:!RC4:!aNULL:!eNULL:!LOW:!3DES:!MD5:!EXP:!PSK:!SRP:!DSS"


host_config:
   "dark-alexandr.net":
      domain_certfile: "/etc/jabber/dark-alexandr.net.pem"

auth_method: sql

sql_type: mysql
sql_server: "localhost"

shaper:
  normal: 1000
  fast: 100000
max_fsm_queue: 2048

acl:
 admin:
  user:
   "user": "dark-alexandr.net"
 local:
  user_regexp: ""

  loopback:
    ip:
      - "127.0.0.0/8"


access:
  max_user_sessions: 
    all: 10
  max_user_offline_messages: 
    admin: 5000
    all: 500
  local: 
    local: allow
  c2s: 
    blocked: deny
    all: allow
  c2s_shaper: 
    admin: none
    all: normal
  s2s_shaper: 
    all: fast
  announce: 
    admin: allow
  configure: 
    admin: allow
  muc_admin: 
    admin: allow
  muc_create: 
    local: allow
  muc: 
    all: allow
  pubsub_createnode:
    local: allow
  register: 
    all: deny
  trusted_network: 
    loopback: allow

language: "en"

modules:
  mod_adhoc: {}
  mod_blocking: {} # requires mod_privacy
  mod_privacy: {}
  mod_caps: {}
  mod_carboncopy: {}
  mod_client_state: {}
  mod_configure: {}
  mod_disco: {}
  mod_last: {}
  mod_muc: 
    access: muc
    access_create: muc_create
    access_persistent: muc_create
    access_admin: muc_admin
  mod_muc_admin: {}
  mod_offline: 
    access_max_user_messages: max_user_offline_messages
  mod_private: {}
  mod_pubsub:
    access_createnode: pubsub_createnode
    ignore_pep_from_offline: false
    last_item_cache: true
    max_subscriptions_node: 100
    plugins: 
      - "flat"
      - "pep"
  mod_roster:
    versioning: true
    store_current_id: true
  mod_ping:
    send_pings: true
    ping_interval: 295
    timeout_action: kill
  mod_vcard: {}
  mod_vcard_xupdate: {}
  mod_mam: 
   default: always
  mod_fail2ban:
    c2s_auth_ban_lifetime: 7200
    c2s_max_auth_failures: 50
  mod_legacy_auth: {}
  mod_s2s_dialback: {}
  mod_stream_mgmt:
     resume_timeout: 600


allow_contrib_modules: true

```


also note what as i said before, i sometime experience this problem too, my implementation is very strictly follow standart, i have researched gajim implementation a bit, and it have workarounds for exactly same problem, it "polls" for pubsub changes instead of relying on events only.
and as i said, standart creator insisted to NOT implement such workarounds...
